### ISSUE TITLE
Rethink realpath check in file serving

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-auth_outage#104]
eg if the sitedir is a symlink this breaks

**Comment by brendanheywood** [comment]
Ok I think the correct way to test this is:

* [ ] concat sitedir + outage dir + file
* [ ] run realpath on it
* [ ] run realpath on just the sitedir + outage dir
* [ ] is the second the suffix of the first then we are good

**Comment by roperto** [comment]
The main worry here is to avoid a path traversal attack.

Considering the user can only request a simple file (no directories involved), a possible solution would be to apply the basename() function on the request data which would remove any type of path in the request.

Cheers,

Daniel

**Comment by roperto** [comment]
The commit above was already merged, solving the issue.
