### ISSUE TITLE
In admin master view, convert to table lib (2 hour)

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-auth_outage#11]
* [ ] make two tables, one for future events listed in soonest order. Link from here to the edit page and the public info page
* [ ] the second table will be past events, it will be listed in most recent first, don't add the edit link

**Comment by roperto** [comment]
I decided to add a new table on top with ACTIVE OUTAGES (will only have one as they won't be able to overlap in the future) which will not show if none found. I think if an admin opens this during an outage or warning time, this is probably the one they want to edit so we can give it focus.

If you disagree it should be easy to move back to only two.
