### ISSUE TITLE
Cannot fetch URL

### ISSUE THREAD

**Issue by Mihailoff** [catalyst/moodle-auth_outage#111]
Version: 1.0.8 / 2016121200 on Moodle 3.1.4

On https://example.com/auth/outage/manage.php there is a red notice
> The outage plugin is not properly configured, please refer to README.md for more information.
> Could not access https://example.com from the server, creation of outages may fail.

When I go to the documentation (https://github.com/catalyst/moodle-auth_outage/blob/master/README.md#installation) there is nothing special to configure. Don't want IP blocking but still added what it suggested in UI. Didn't touch config.php

When new event is created it ends up with an error:

```
Cannot fetch: https://example/auth/outage/info.php?auth_outage_hide_warning=1&id=3
line 73 of /auth/outage/classes/local/controllers/maintenance_static_page_io.php: call to debugging()
line 64 of /auth/outage/classes/local/controllers/maintenance_static_page.php: call to auth_outage\local\controllers\maintenance_static_page_io::file_get_data()
line 167 of /auth/outage/classes/local/outagelib.php: call to auth_outage\local\controllers\maintenance_static_page::create_from_outage()
line 138 of /auth/outage/classes/dml/outagedb.php: call to auth_outage\local\outagelib::prepare_next_outage()
line 45 of /auth/outage/edit.php: call to auth_outage\dml\outagedb::save()

Warning: DOMDocument::loadHTML(): Empty string supplied as input in /var/www/data/default/lms/auth/outage/classes/local/controllers/maintenance_static_page.php on line 95
```

**Comment by roperto** [comment]
The probable cause is that your Moodle server cannot see its own site. Are you running it on a VM? If yes, please check if if the VM can browse Moodle. In some cases it can be solved by adding a line in `/etc/hosts` (linux) or `C:\Windows\System32\drivers\etc\hosts` (windows).

Can you give me some feedback if that worked?

I am also keen to implement enhancement  #99 , which removes the dependency on CURLing pages (would probably remove that requirement as well).

**Comment by danmarsden** [comment]
closing due to lack of response from original reporter after request for further feedback.
