### ISSUE TITLE
Bad redirect in manage.php

### ISSUE THREAD

**Issue by rebeltg** [catalyst/moodle-auth_outage#112]
Line 33 in manage.php has a hard reference to the website root (/auth/outage/manage.php). This results in a 404 error on sites where Moodle is not in the root (example.com/moodle for example) after saving an outage. It should reference the Moodle web root from config.php (something like `set_url("$CFG->wwwroot/auth/outage/manage.php");`

**Comment by roperto** [comment]
Hi @rebeltg 

I was checking the code, on line 34 it is using a `moodle_url` object with handles the subpath.

The problem you are getting on line 33 is probably related to the authentication plugin not being enabled, in which case there is no section called `auth_outage_manage` in the administation settings menu.

I just created issue #113 as an enhancement to address that.

Can you please check that `/admin/settings.php?section=manageauths` has the Authentication Plugin enabled?

Please let me know if that solves the problem.

**Comment by roperto** [comment]
I didn't mean to close before getting you feedback. Please let me know if it worked. Thanks.

**Comment by rebeltg** [comment]
Good afternoon @roperto,
Thank you for the claification on how that function in Moodle works; I had misunderstood it. The plugin is enabled on the Manage Authentication page. It appears that the version in the Moodle repository is not the same as the current branch in Github. I've updated an the redirect seems to be fixed. My appologies for not checking this first.
Thank you,
Blair
