### ISSUE TITLE
Outage bar needs to add class to body when active

### ISSUE THREAD

**Issue by meepster-nz** [catalyst/moodle-auth_outage#115]
When the outage bar is active, there is no body class applied. When then dock is active and the outage bar, overlapping occurs. With the body class, then at least we can manipulate the css to fix any display issues.

**Comment by brendanheywood** [comment]
This should be done just like the envbar like this:

https://github.com/catalyst/moodle-local_envbar/blob/master/renderer.php#L170-L172

**Comment by roperto** [comment]
Fixed with pr #116
