### ISSUE TITLE
Auto start maintenance mode causes a corrupt page 

### ISSUE THREAD

**Issue by aspark21** [catalyst/moodle-auth_outage#148]
Auto start maintenance mode causes a corrupt page 
Tested on:
Moodle latest MOODLE_34_STABLE and MOODLE_36_STABLE
Plugin: master@e94d9c94eae8b4a01e2580ca1f74085fc1bb208c

If one schedules an outage with the "Auto start maintenance mode" setting ticked, the site goes all corrupt when the maintenance mode starts.
This doesn't happen when the outage is scheduled without "Auto start maintenance mode" and the site is put into maintenance mode manually.

**Comment by Richardvi** [comment]
Confirmed, same here.

**Comment by aspark21** [comment]
From some other testing, I'm wondering now whether this is because this plugin starts a Moodle CLI Maintenance Mode rather than a standard Moodle Maintenance mode.

**Comment by brendanheywood** [comment]
I ran into this too recently

**Comment by golenkovm** [comment]
I believe this issue should be fixed as part of #172 and #174
