### ISSUE TITLE
cannot fetch errors in logs. (wwwroot is in sub directory)

### ISSUE THREAD

**Issue by katcher** [catalyst/moodle-auth_outage#179]
I have just installed the plugin on our sandbox v3.5.10.

I see the following error in my logs whenever the plugin is active:

Cannot fetch: https://moodle-snbx.XXXX.ca/moodle/theme/styles.php/_s/boost/1580739700_1580219463/data:image/svg+xml;charset=utf8,%3Csvg xmlns=\
line 73 of /auth/outage/classes/local/controllers/maintenance_static_page_io.php: call to debugging()
line 235 of /auth/outage/classes/local/controllers/maintenance_static_page_io.php: call to auth_outage\local\controllers\maintenance_static_page_io::file_get_data()
line 164 of /auth/outage/classes/local/controllers/maintenance_static_page_generator.php: call to auth_outage\local\controllers\maintenance_static_page_io->save_url_file()
line 134 of /auth/outage/classes/local/controllers/maintenance_static_page_generator.php: call to auth_outage\local\controllers\maintenance_static_page_generator->update_link_stylesheet_parse()
line 82 of /auth/outage/classes/local/controllers/maintenance_static_page_generator.php: call to auth_outage\local\controllers\maintenance_static_page_generator->update_link_stylesheet()
line 121 of /auth/outage/classes/local/controllers/maintenance_static_page.php: call to auth_outage\local\controllers\maintenance_static_page_generator->generate()
line 166 of /auth/outage/classes/local/outagelib.php: call to auth_outage\local\controllers\maintenance_static_page->generate()
line 138 of /auth/outage/classes/dml/outagedb.php: call to auth_outage\local\outagelib::prepare_next_outage()
line 44 of /auth/outage/edit.php: call to auth_outage\dml\outagedb::save()

**Comment by katcher** [comment]
More, cannot get rid of navbar message!

**Comment by katcher** [comment]
figured out second issue.  

While exploring, i opened the admin appearance Additional HTML
In the 
When BODY is opened:  I removed the content of the textarea which was the warning bar information.

I was now able to remove the outage navbar.  Is that a normal behavior?

**Comment by danmarsden** [comment]
Hey Eric - I don't think we've seen the cannot fetch errors before, and we've used this plugin on a lot of 3.5 sites - I don't personally spend a lot of time on this plugin either - let us know if you work anything else out!

**Comment by brendanheywood** [comment]
@golenkovm has reproduce this, he's fixing this now

**Comment by golenkovm** [comment]
Hey @katcher 
This issue has been fixed via #183 
Feel free to update your plugin and re-test. Please let me know if there any issue
