### ISSUE TITLE
Error following 3.5.11 merge

### ISSUE THREAD

**Issue by katcher** [catalyst/moodle-auth_outage#189]
I upgraded my dev site to moodle 3.5.11 from 3.5.10 and was unable to navigate to my site.  The log showed the following error:

[Mon Mar 09 09:29:44.022165 2020] [php7:error] [pid 13078] [client 10.102.143.6:36813] PHP Fatal error:  Uncaught Error: 
Class 'core\\ip_utils' not found in /public/home/moodle/lib/moodlelib.php:9034
Stack trace:
#0 [internal function]: {closure}('10.102.143.6')
#1 /public/home/moodle/lib/moodlelib.php(9035): array_filter(Array, Object(Closure))
#2 /public/home/moodle/lib/moodlelib.php(8997): getremoteaddr(NULL)
#3 /public/moodledata/live/climaintenance.php(5): remoteip_in_list('10.102.143.6')
#4 /public/home/moodle/auth/outage/bootstrap.php(82): require('/public/moodled...')
#5 /public/home/moodle/config.php(511): require('/public/home/mo...')
#6 /public/home/moodle/login/index.php(27): require('/public/home/mo...')
#7 {main}
  thrown in /public/home/moodle/lib/moodlelib.php on line 9034

I renamed the /public/moodledata/live/climaintenance.php and was able to access as expected.
The site seems to function appropriately so I do not think it is caused by the upgrade to 3.5.11.

I created another outage and saw the same error in the logs.  Also, the auth_outage/climaintenance folder in the data directory was full of entries.  

I removed all entries and recreated an empty auth_outage folder in moodledata directory.

**Comment by katcher** [comment]
I think I found a solution. 

climaintenance.php needs to require_once the lib/classes/ip_utils.php

Eric

**Comment by katcher** [comment]
I added the require_once but now i see a notice error.


 Undefined property: stdClass::$reverseproxyignore in /public/home/moodle/lib/moodlelib.php on line 9034, referer: https://xx.yy.ca/moodle/auth/outage/manage.php

Still works though without error

**Comment by katcher** [comment]
MDL-68125 core: Fixed $CFG->reverseproxyignore install regression.  I still needed to leave the ip_utils.php require.

**Comment by brendanheywood** [comment]
This tracker fixes reverseproxyignore, which completely coincidentally was my mistake :/

https://tracker.moodle.org/browse/MDL-68125

Can you make a pull request please for the other part?

**Comment by katcher** [comment]
Hi Brendan, I did notice the patch for reverseproxy and applied it to our dev site.  I do not know what you mean by create another pull request.  I probably should but…

Eric

**Comment by katcher** [comment]
Tried to do a pull request.  Hope i did it properly.

**Comment by brendanheywood** [comment]
thanks again @katcher
