### ISSUE TITLE
PHP Notice Error from bootstrap.php

### ISSUE THREAD

**Issue by katcher** [catalyst/moodle-auth_outage#196]
Server log displays following error when course is accessed moodle 3.9
Undefined variable: root in /public/home/39/auth/outage/bootstrap.php on line 74,

**Comment by brendanheywood** [comment]
thanks @katcher should be fixed now, please retest

**Comment by katcher** [comment]
Hi Brendan, giving a different error now!
My site is in a subdir
The error now:
Undefined index: url in /public/home/39/auth/outage/bootstrap.php on line 74

for debug I printed out the parse_url of wwwroot
Array
(
    [scheme] => https
    [host] => moodle-snbx.xxx.yy
    [path] => /39
)

I am guessing that path should be 
$path = $rooturl['path'];
