### ISSUE TITLE
Add admin tester only period, optionally restrict by ip

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-auth_outage#2]
- [x] implement a config item to store the list of valid ips when in lockdown mode. There should also be a check somewhere that the admin's current ip is in the whitelist, if not then show a warning but allow it

Effectively we want the site to be in 'cli maint' mode but only for people who are coming from random ip's, people in the whitelist are ok. The fake maint mode is not sufficient and happens way too late in the bootstrap process, we need to add our ip check very early, somewhere around setup.php line 314. But we also don't want to hack core. And we want this to be configurable from the GUI. But we don't have access to the database or config at this point....

So what we will do is in config.php do a small check for a file inside sitedata, if it exists then include it. It will contain some logic to parse the remote ip's from it, then do the check. For simplicity I'd make this file $CFG->sitedata . '/climaintenance.php'. We could possibly even see if core wanted that
- [x] add this to config.php (add this to install notes, and later to docker templates)

```
if (file_exists("$CFG->dataroot/climaintenance.php")) {
  require("$CFG->dataroot/climaintenance.php");
} else {
  $CFG->auth_outage_check = 1;
}
```
- [x] We need to test how that behaves with opcache etc on, this file can be cached for a little bit but not for ages. If any issues then change the extension?
- [x] if ip block is on, then when we create the outage template file also create this file. This file should not only do the ip check but also check the time so we can create this file in advance without killing the site
- [x] if you close an outage or update an outage then create or remove this file as needed

If the check fails then we will jump directly in cli maint mode, eg either put moodle into maint mode, or possible just server the maint file directly itself (but assumes the climain file exists)

This check needs to be as light weight as possible because it will run on every page load. It also needs to be as tiny and as generic as possible as we want to inject this into the config.php template made by CI probably into all moodle's so it may run even if the outage plugin isn't installed.

Also we won't yet have access to moodelib.php in order to use remoteip_in_list(), so experiement with including that one file earlier. There may be side effects so if that doesn't work then we need to implement our own ip filter (but I really don't want to!!! See https://gist.github.com/tott/7684443). 

The plugin should be able to check if the config.php code snippet has been correctly installed because '$CFG->auth_outage_check = 1' that way we can test in the GUI that the ipblock is going to work later on. For an example of a settings check see here: https://github.com/brendanheywood/moodle-local_cleanurls/blob/master/settings.php#L39

Also it may be useful to be aware of the patch that Dima made here, but I don't think that much is directly transferable: https://github.com/SREd-URV/moodle-auth_ip/pull/7/files

**Comment by roperto** [comment]
I am closing this, there are bugs still left to fix but they have their own issues:

* https://github.com/catalyst/moodle-auth_outage/issues/72
* https://github.com/catalyst/moodle-auth_outage/issues/71
* https://github.com/catalyst/moodle-auth_outage/issues/70

Also the enhancement (ipblock allowed per outage):

* https://github.com/catalyst/moodle-auth_outage/issues/69
