### ISSUE TITLE
Broken unit tests

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-auth_outage#213]
Seems like tests are broken after the recent changes.

Would be good to fix travis to make sure that we don't break them again.

.......E

Time: 12.82 minutes, Memory: 354.30 MB

There was 1 error:

1) infopagecontroller_test::test_output
Error: Call to undefined method auth_outage\local\outagelib::inject()

/var/www/site/auth/outage/classes/local/controllers/infopage.php:111
/var/www/site/auth/outage/classes/local/controllers/infopage.php:85
/var/www/site/auth/outage/tests/phpunit/local/controllers/infopage_test.php:106
/var/www/site/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "infopagecontroller_test" auth/outage/tests/phpunit/local/controllers/infopage_test.php

**Comment by golenkovm** [comment]
It seems to be a regression of #212  @jamie-catalyst

**Comment by jamie-catalyst** [comment]
I've created a fix to get the tests running again which fixes any errors being flagged, including the issue highlighted by @dmitriim
