### ISSUE TITLE
Outage banner overlaps page content

### ISSUE THREAD

**Issue by golenkovm** [catalyst/moodle-auth_outage#222]
Here is a few screenshots how does it look like:

1) Grading page:
![image](https://user-images.githubusercontent.com/22066290/103067504-2c806d80-460f-11eb-9650-cf2e575307b1.png)

2) Main dashboard (_Customize this page_ is covered):
![image](https://user-images.githubusercontent.com/22066290/103067574-546fd100-460f-11eb-9dae-7405c9130369.png)

3) Forum grading page:
![image](https://user-images.githubusercontent.com/22066290/103067668-897c2380-460f-11eb-90ff-df470ab84515.png)

And many others (Site admin, course, activities and so on). 

Seems to be a regression of #211

**Comment by brendanheywood** [comment]
Every theme is different, we will at best be able to get this working with boost but each theme needs custom config to make it work

**Comment by mattporritt** [comment]
I'm looking at #223 PR for this.
Agreed this will fix the issue for Boost, and for that reason I'm happy to merge it in. As this needs to be done anyway
However, @brendanheywood pointed out. This will not fix it for all themes. A more universal fix would be to add a config setting to add a "theme offset" that should default to work for boost, but allow admins to adjust for their sites theme

**Comment by golenkovm** [comment]
Thank you @mattporritt 
I've just created a new issue for the universal fix.
Closing this off.
