### ISSUE TITLE
3.11 fatal error

### ISSUE THREAD

**Issue by aspark21** [catalyst/moodle-auth_outage#253]
Moodle 3.11.0
auth_outage latest master

` 'PHP Fatal error:  Cannot declare class events_test, because the name is already in use in /var/www/html/auth/outage/tests/phpunit/event/events_test.php on line 158'`

**Comment by danmarsden** [comment]
Please see the readme for the supported branches. Master is deprecated and will be deleted soon.

**Comment by aspark21** [comment]
OK, reran it with MOODLE_39_STABLE and it's the same thing though.

**Comment by danmarsden** [comment]
Thanks -  I have this in a Moodle master (4.0) branch and it isn't tiggering this - it's obvious that class name is incorrect, but it would be good to know if there's another plugin with an incorrectly named class that we need to fix as well? - did you see where else it was being used?

**Comment by aspark21** [comment]
The only place I’ve found it so far is here https://github.com/moodle/moodle/blob/MOODLE_311_STABLE/badges/tests/events_test.php#L34

changed recently - https://github.com/moodle/moodle/commit/c2c04214bb6de07e1fe8cac213e3c6da64a80c5a
By https://tracker.moodle.org/browse/MDL-70963

But I see Eloy realised this exact problem would happen 5 days after it was integrated
https://tracker.moodle.org/browse/MDL-71049

**Comment by danmarsden** [comment]
thanks for the links - are you running individual tests in your CI rather than a full run? - we're doing most of ours in a full run which is why we haven't seen this yet?

**Comment by aspark21** [comment]
Full runs.

I was finding a lot of fatals with our 3.11 build due to all the PHPUnit changes in 3.10 & 3.11 haven't finished getting through it fatal free yet; I'm on leave for a couple of weeks but I'll have a look when I'm back if I can see any other plugins doing this.
