### ISSUE TITLE
Outage manager banner masks messaging/notification, impeding usability

### ISSUE THREAD

**Issue by l33cu** [catalyst/moodle-auth_outage#266]
Hi team

We've noted that default styling of the outage manager bar seems to hide some key features, namely notification bell icon and messaging icon.

We'd like to be able to have the banner in place without disrupting the placement of these commonly used interface icons.

Kind Regards
Lee Cujes

**Comment by brendanheywood** [comment]
hi Lee, the plugin comes with default styles that do work with the vanilla boost theme. There are admin settings for overriding the default style of the navbar so it can be made to work with any other theme. Please make a wr and we'll sort that internally.

**Comment by l33cu** [comment]
Thank you Brendan. I think that gave me enough information to resolve this
myself. We had some errant CSS applied, that was causing problems.

Kind Regards
Lee Cujes

**Comment by brendanheywood** [comment]
Great stuff Lee. Also make sure this config is done in all envs including prod so when it is refreshed back to the other envs you don't lose it
