### ISSUE TITLE
Update README images for readability on dark themed github

### ISSUE THREAD

**Issue by keevan** [catalyst/moodle-auth_outage#278]
In github dark theme, it's hard to read the text on the images. It would be good to make sure it's readable regardless of github's theming choices.

![image](https://user-images.githubusercontent.com/9924643/149432981-bd2479df-235d-4172-8cf4-6a537a987a13.png)

Potentially it might be okay as plaintext above each image snippet instead.

**Comment by brendanheywood** [comment]
Converted to an image instead of svg with transparent bits
