### ISSUE TITLE
Cosmetic polish for the bar

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-auth_outage#29]
* [x] make the bar white on red, remove the dotted border
* [x] make the whole outage title a link, remove the [ ], make the link white too
* [x] remove the ellipsis
* [x] make the long form dates include both the day in short form 'Sun' and the timezone offset
* [x] The messages need to be a bit shorter change 'Our system will be under maintenance until ' to 'System should be back at ' or something else nice and short

**Comment by roperto** [comment]
Quick preview:
![ongoing](https://cloud.githubusercontent.com/assets/3672494/18495878/8cb066a4-7a64-11e6-89ef-270ee372e2e4.png)
![warning](https://cloud.githubusercontent.com/assets/3672494/18495877/8caa8d92-7a64-11e6-9b4a-f5dd6d517c02.png)

**Comment by brendanheywood** [comment]
More todos:

* [ ] fix the padding and change the height to min-height so it works and wraps on smaller screens
* [ ] add some css, or <nobr> around the groups of words to make them wrap nicer, or add some css to scale this down on small devices so it never wraps.
