### ISSUE TITLE
Behat test failing - warningbar.feature

### ISSUE THREAD

**Issue by AdilIqbal95** [catalyst/moodle-auth_outage#294]
Hi, the test stated above is failing.

**Environment details:**
MySQL 5.7
PHP 7.4
Moodle latest MOODLE_311_STABLE

**Error details:**
Scenario: This is how an outage should happen without maintenance mode and manual finish.

Then I should see "We are back online!" in the warning bar: Xpath matching locator "/descendant-or-self::*[contains(., 'We are back online!')][count(descendant::*[contains(., 'We are back online!')]) = 0]" not found. (Behat\Mink\Exception\ElementNotFoundException)

**Comment by danmarsden** [comment]
thanks - this is really a duplicate of #243 - feel free to help us by submitting a PR.

**Comment by AdilIqbal95** [comment]
Aplogies, didn't see that. Unfortunately I don't currently have the capacity to do so.
