### ISSUE TITLE
Behat test failing - default_settings.feature

### ISSUE THREAD

**Issue by AdilIqbal95** [catalyst/moodle-auth_outage#295]
Hi, the test stated above is failing.

**Environment details:**
MySQL 5.7
PHP 7.4
Moodle latest MOODLE_311_STABLE

**Error details:**
Scenario Outline: Check if I can save the default settings.

And I set the following fields to these values:: Field matching locator "s_auth_outage_default_autostart" not found. (Behat\Mink\Exception\ElementNotFoundException)

**Comment by danmarsden** [comment]
thanks - this is really a duplicate of #243 - feel free to help us by submitting a PR.

**Comment by AdilIqbal95** [comment]
Apologies, didn't see that, thanks for letting me know. Unfortunately I don't currently have to capacity to fix this.
