### ISSUE TITLE
Moodle 4.0 support?

### ISSUE THREAD

**Issue by durzo** [catalyst/moodle-auth_outage#303]
any plans to release a 4.0 version?

**Comment by danmarsden** [comment]
We have a number of 4.0 sites with this plugin installed. Please report any specific issues you find while testing it in 4.0. Note we do not regularly publish all our plugins to the plugins db as we use git to deploy our plugins internally. We have been rolling out auto deployment to plugins db on version.php file update (which has been deployed here) but if you rely on plugins db you will need to wait for us to do that or submit a pull request to bump the versions in the version.php file. Thanks.
