### ISSUE TITLE
Default settings not set on install causing undefined offsets

### ISSUE THREAD

**Issue by sarahjcotton** [catalyst/moodle-auth_outage#306]
The admin settings page is bypassed on install so the next time the settings page is loaded undefined offsets are thrown as the defaults haven't yet been set.

```
Warning: Trying to access array offset on value of type null in /var/www/moodlemysql/lib/adminlib.php on line 4053
Warning: Trying to access array offset on value of type null in /var/www/moodlemysql/lib/adminlib.php on line 4059
```

**Comment by danmarsden** [comment]
@sarahjcotton can you please include the full undefined offset error messages here - helps with others google searching an error, but also with the PR process to ensure the code is going in the right place.
