### ISSUE TITLE
Function strftime deprecated in php 8.1

### ISSUE THREAD

**Issue by SashaAnastasi** [catalyst/moodle-auth_outage#319]
Moodle 4.2 has a core function to replace it: \core_date::strftime
I've created a branch with this fix [here](https://github.com/SashaAnastasi/moodle-auth_outage/tree/m42-php81-compat)
This branch needs a Moodle 4.2 target branch.

Tōtara 17 has a core function to replace it: \totara_core\strftime::format
I've created a branch with this fix [here](https://github.com/SashaAnastasi/moodle-auth_outage/tree/t17-php81-compat)
This branch needs a Tōtara 17 target branch.

**Comment by danmarsden** [comment]
I was initially leaning towards writing a if class exists style function in there to support all the versions/forks... but... do we actually need to print a timestamp there at all? - I'm inclined to just delete that call completely!

**Comment by danmarsden** [comment]
scrap that... Brendan rightly points out we could just do something like userdate(time()) in there instead.

**Comment by danmarsden** [comment]
fixed in #320
