### ISSUE TITLE
Return to previous page after outage is over (30 mins)

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-auth_outage#34]
The implementation of this may depends on other stuff. The use case is after the outage page is prebake, instead of redirecting to the info page when the bar counts down, we can just reload the current page will then show the static maintenance page.

If auto start is not set, then redirect to the info page with an extra query param ?wantsurl=blah. If you have a wantsurl, and the outage is now over, then redirect back to this page.

**Comment by roperto** [comment]
There is no more redirection to the info page. The info page is only shown if you click on the warning bar message to read more about it.

As of now, the user can still browse around if auto start is not set but the red warning message will stay there, alerting that the website can be taken down at any moment (or he may be reading or watching a video, as discussed in issue #32 .

I am closing this issue without any implementation, if we need to change the use cases we can create a new one explaining how the plugin should behave.

Daniel
