### ISSUE TITLE
4.5 Fatal Error - Cannot make static method non static 

### ISSUE THREAD

**Issue by aspark21** [catalyst/moodle-auth_outage#343]
Moodle: 4.5 dev
PHP: 8.1

`
PHP Fatal error:  Cannot make static method advanced_testcase::get_fixture_path() non static in class auth_outage\local\controllers\maintenance_static_page_test in /var/www/html/auth/outage/tests/local/controllers/maintenance_static_page_test.php on line 340'`

**Comment by danmarsden** [comment]
I think the solution here might just be to rename the function in the maintenance_static_page_test class as the get_fixture_path() function is now a new core function in 4.5
