### ISSUE TITLE
Support for Moodle 4.5

### ISSUE THREAD

**Issue by ElectricCircus** [catalyst/moodle-auth_outage#349]
Will be nice to have an updated version supporting Moodle 4.5.x

**Comment by danmarsden** [comment]
Hi there, 

We do have this running on some 4.5 sites, but it hasn't been tested fully  - if you would like to speed up the process, the best thing to do would be to download the latest version from github and test it in your own 4.5 site and then report any specific issues you find here to github. Or alternatively - a comment to say "I've tested this in 4.5 and it works well".

thanks!
