### ISSUE TITLE
Create a video screen cast of the plugin and add to plugin directory and README

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-auth_outage#36]
Demo:
- [x] setup scheduled from admin side
- [x] preview of an outage for an admin
- [x]  create an adhoc outage from cli, start in 5 seconds, go for 5 seconds

**Comment by roperto** [comment]
Link: https://youtu.be/XbF1RvarMAw

**Comment by roperto** [comment]
Apparently my moodle-plugin-ci was not checking for PhpDocs, I am not sure why.

Several PHPDocs errors were raised when submitting the plugin, I will fix them ASAP.

**Comment by roperto** [comment]
Published: https://moodle.org/plugins/auth_outage
