### ISSUE TITLE
External problem (theme)

### ISSUE THREAD

**Issue by roperto** [catalyst/moodle-auth_outage#40]
Hi Brendan, I think it is not related to this plugin but I am not sure where to put, you can move it to the proper place.

The following files are using PHP short opening tags and are not being processed by my PHP engine (probably not by some others as well).

theme/catalyst/layout/columns3.php:    <? require('cat-head.php'); ?>
theme/catalyst/layout/columns1.php:    <? require('cat-head.php'); ?>
theme/catalyst/layout/columns2.php:    <? require('cat-head.php'); ?>

Cheers

**Comment by brendanheywood** [comment]
Fix it here and push it directly to master:

https://git.catalyst-au.net/elearning/moodle-theme_catalyst
