### ISSUE TITLE
Related to Issue #21 - An not-automatic-start outage followed by an automatic-start outage will produce the wrong static page.

### ISSUE THREAD

**Issue by roperto** [catalyst/moodle-auth_outage#44]
Consider the scenario:
* A = Outage starting in 1 hour, no auto-maintenance flag.
* B = Outage starting in 2 hours, *with* auto-maintenance flag.

It will generate the static page for Outage A and set `maintenance_later` for Outage B.

Once Outage B starts, there is a big chance the static page will still be set for Outage A, providing wrong information.

Any suggestions with that?

**Comment by brendanheywood** [comment]
Ignore this, it will be fixed by a cron, it's on the list somewhere already
