### ISSUE TITLE
The refresh is hard coded to 5 minutes, this should instead be the same as the outage duration

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-auth_outage#53]

**Comment by roperto** [comment]
Hi Brendan,

I put 5 minutes because an outage can finish earlier than the duration, but if you prefer the duration please let me know and I will change it.

What do you prefer?

-- Daniel

**Comment by brendanheywood** [comment]
I want service resume as soon as possible and it should be in sync with the outage window

**Comment by roperto** [comment]
I will leave 5 minutes then, we could pool in smaller or bigger amounts of time, I know my five minutes is a little arbitrary. I am open to suggestions.

Cheers,
Daniel

**Comment by roperto** [comment]
The hardcoded value you mentioned was probably the javascript, I was thinking about the static page. Static page is every 5 minutes (I cannot know the correct time to use because it is static). JavaScript is to `Math.min(time_to_stop or 5_minutes)` as time to stop could be large but it finishes earlier. Commit will appear below soon.

**Comment by brendanheywood** [comment]
I'm talking about this line

https://github.com/catalyst/moodle-auth_outage/blob/master/views/info/static.php#L38

This should not be hard coded, it should be the planned outage length

**Comment by roperto** [comment]
I am probably misunderstanding something, this is how I am thinking:

If we leave the planned duration for the refresh time, if someone enters the website a few seconds before the outage is finished, he will get the static page with the whole outage duration. I cannot know how much time left in the static page.

Sorry, I am not getting exactly what you mean. If you prefer I can just change it to the duration and later you explain to me.

Cheers,

Daniel

**Comment by brendanheywood** [comment]
I think you are over thinking it. Yes just change it to the outage length.

**Comment by roperto** [comment]
No worries, new code:
https://github.com/catalyst/moodle-auth_outage/commit/e09ae44f2f4cc827e731a2ea2c4dc182a63381e1#diff-8f6f9f5fb4e6c8101a8f7c394d4c50a4R38

**Comment by brendanheywood** [comment]
Cool, only thing I'd do differently is in the assertion use an explicit value, testing against itself doesn't actually test it is the expected value.

**Comment by roperto** [comment]
You are right. I will change that.
