### ISSUE TITLE
Talk to Brendan on 2016-08-31

### ISSUE THREAD

**Issue by roperto** [catalyst/moodle-auth_outage#6]
As discussed on the phone:
* [ ] Rename branch to [feature]-[issue] such as mvp-1
* [ ] Allow internationalization (get_string)
* [ ] Menu placement -- @brendanheywood can you confirm that?
* [ ] Improve validation as:
** [ ] Can only create outages that start in the future
** [ ] Cannot delete/edit outages that already ended
* [ ] Add crumb trail information
* [ ] Improve outage list, make it as a table
** start | duration | title-description | created-modified | actions
* [ ] Add logging
* [ ] Link to calendar as described on Issue #1
* [ ] Change 'description' to 'public description'

**Comment by brendanheywood** [comment]
closing this as it's now split up into different issues
