### ISSUE TITLE
local_outage plugin should use a different repo/branch

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-auth_outage#60]
looks like the local_outage folder is a plugin? - only used when the user wants to use this with 2.8 or lower? - it really shouldn't be in the master branch and ideally should probably be in a separate repo.

https://github.com/catalyst/moodle-auth_outage/tree/master/local_outage

**Comment by roperto** [comment]
Fixed in v1.0.3

https://github.com/catalyst/moodle-auth_outage/commit/c49c854a8924bfda5dfb1fa71a4cdcd1a1c4770d

Thank you for the feedback.
