### ISSUE TITLE
What to do when $CFG->maintenance_message is set?

### ISSUE THREAD

**Issue by roperto** [catalyst/moodle-auth_outage#75]
It will not use the template ...

**Comment by brendanheywood** [comment]
Ok just looked at core code, so this simply can't work side by side with the auth/outage so I think we either forcefully remove this config item, or we warn on the setting page that it will break. Probably the latter is more friendly so lets do that, do another check that spits out a $OUTPUT->notification if it is set

**Comment by roperto** [comment]
We are logging it then disabling as it would affect the outage manager plugin.
