### ISSUE TITLE
Use outage bootstrap.php to inject the warning bar.

### ISSUE THREAD

**Issue by roperto** [catalyst/moodle-auth_outage#76]
There are some cases where it should not be injected, but I think the 'injection' function should handle them.

How is this going to merge with additional HTML written in the database? Is it going to overwrite it?

What do you think? If it works maybe we could even abandon the traditional hooks.

Cheers,
Daniel

**Comment by brendanheywood** [comment]
Hmm, it is too early in the bootstrap process to access the $PAGE or append anything to $CFG->additionalhtmltopofbody (we can't just set it either), and not late enough to inject something directly at the right time. I like the concept but don't think it's viable

I think we should just keep pushing for additional hooks such as in https://tracker.moodle.org/browse/MDL-53978
