### ISSUE TITLE
Outage bar not appearing on settings page

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-auth_outage#85]
eg this page shows no bar

https://ltu-prod.catalyst-au.net/admin/settings.php?section=authsettingoutage

![image](https://cloud.githubusercontent.com/assets/187449/21127773/ab9f8b2c-c149-11e6-878b-cf181b1d97e5.png)

but this page does show the bar:

https://ltu-prod.catalyst-au.net/auth/outage/manage.php

![image](https://cloud.githubusercontent.com/assets/187449/21127796/e511eecc-c149-11e6-9a92-cb9521dc2b62.png)

**Comment by roperto** [comment]
Hi @brendanheywood ,

This is done deliberately at:
https://github.com/catalyst/moodle-auth_outage/commit/f1b5959aff0a3c71a516937c95e22b02189f54e2#diff-22d529a102897a7b88c1fe90bcd902f2R185

Regarding to issue:
https://github.com/catalyst/moodle-auth_outage/issues/65

Should I revert that?

Cheers,

**Comment by roperto** [comment]
We decided to remove only from settings.php with the additional html section. Searching will still not be covered by this fix.
