### ISSUE TITLE
Wrong class using in warnings

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-auth_outage#87]
This error is using 'notifyfailure' which doesn't exist. It should be 'warning' or a legacy one like 'notifyerror':

![image](https://cloud.githubusercontent.com/assets/187449/21129832/9ae65bd0-c158-11e6-8407-3550ff0efae3.png)

**Comment by roperto** [comment]
Using 'notifyerror' instead. I have no idea why I used 'notifyfailure'.
