### ISSUE TITLE
During an ipblocked outage, if anything triggers the outage template generation, it may reactivate cli maintenance mode.

### ISSUE THREAD

**Issue by roperto** [catalyst/moodle-auth_outage#93]
Given

* You started an outage with auto-start maintenance mode.
* You finished the maintenance mode.

When
* You  change an outage (not finish) or the IPs blocked settings.

Then:
* The maintenance mode is reactivated.

**Comment by roperto** [comment]
Possible fixes:

- Do now allow to enter automatically enter maintenance mode if in the past.

or

- Track if the outage already triggered maintenance mode and disallow it to trigger it twice.

I prefer the first option for two reasons:

1) Simpler (check time before maintenance_later call), other solution would involve creating a field in the database.

2) It also prevents from acidentally triggering maintenance mode from GUI, you at least have a few minutes to revert it before it kicks in.

**Comment by brendanheywood** [comment]
I prefer the first. If the start is in the past then don't set maintenance_later

**Comment by roperto** [comment]
Done as option 1:

Do now allow to enter automatically enter maintenance mode if in the past.
